# ArgoCD Application: Fluent Bit Log Pipelines
# Fluent-bit CRD 기반 로그 수집 파이프라인 (Input/Parser/Filter/Output)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-pipelines
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/kronenz/monitor-stack.git
    targetRevision: main
    path: manifests/log-pipelines/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
