# ArgoCD Application: Fluent Operator
# Fluent Bit DaemonSet 및 CRD 컨트롤러 배포
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-fluent-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/kronenz/monitor-stack.git
    targetRevision: main
    path: manifests/logging/fluent-operator/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
