# ArgoCD Application: Data Prepper
# Fluent Bit에서 로그를 수신하여 OpenSearch로 전달
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-data-prepper
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/kronenz/monitor-stack.git
    targetRevision: main
    path: manifests/logging/data-prepper/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
